### PR TITLE
Workaround for TFS/VSTS API limitation (issue #349)

### PR DESCRIPTION
**Pull request by ReneSchumacher**
### What problem does this PR address?
There is a limitation in the TFS/VSTS build APIs that can lead to incomplete list of work items associated to a build.
  
### Is there a related Issue?
Yes, see issue #349 

### Testing
The PR has not been thoroughly tested yet as I am just building a sample project that exhibits the problem and allows testing. I will update the PR with a comment once that is done. Any additional testing with existing standard builds/releases is highly appreciated ;-)

### CODE REVIEW

**Comment by ReneSchumacher** [comment]
First tests showed that the API to get changes associated to a build also has the 200 changes limitation. Thus, I have more work to do before the workaround fixes all problems.

**Comment by rfennell** [comment]
I am away this weekend, I will try to look at this when I get back

**Comment by rfennell** [comment]
@ReneSchumacher Just to explain the merge issue that is in the PR, when I release I pop a line like

- 1.2  PR123 by @Fred Fix for this or that

It really helps if you can update the readme, just increment the .x number, saves me doing it

**Comment by rfennell** [comment]
@ReneSchumacher Another point to note the the V1 of Xplat version is in effect locked now, it was left in when @gregpakes did a complete re-write with a breaking change (a flag needed to changed) so as to not break people process out the box. We had assumed that all changes would just be done on the V2 task - to reduce the areas for change

**Comment by ReneSchumacher** [comment]
@rfennell The workaround is now fixed, although there's only a solution for Git repos. The TFVC APIs don't provide the necessary capabilities to implement a workaround.

I already tested the PowerShell version and will now start to test the xplat version.

Btw: I already imported the changes from master into my topic branch before you did it. Thus, history now looks a bit more complex than it should be. If you like, I can fix that via a force push.

**Comment by rfennell** [comment]
Thanks for sorting that merge, don't worry about the history, next like a forced push myself 

It will all be sorted by a squash that I usually do in the end.

Thanks for your efforts

**Comment by rfennell** [comment]
Sorry mean to remind you, I would only look at the V2 Xplat version, the V1 is depricated

**Comment by ReneSchumacher** [comment]
Sure, I only changed V2 of the Xplat version.

**Comment by ReneSchumacher** [comment]
@rfennell My tests have been successful. I have tested the PowerShell version in a build (not in a release) and the Xplat V2 in a release. Both now return more than 200 commits and all work items as expected.

**Comment by rfennell** [comment]
I am way on holiday week coming, I will have look when I get back

**Comment by ReneSchumacher** [comment]
Hey @rfennell, are you back from vacation?

**Comment by rfennell** [comment]
Yes I am and I am sorting a release, just have an issue with my automated test pipeline at present. If I can't resolve it I will bypass it and do a manual step of that phase. So I am on it

**Comment by rfennell** [comment]
The powershell version has been released as 2.22.1

**Comment by rfennell** [comment]
The Xplatversion is released as 2.5.2

**Comment by rfennell** [comment]
@ReneSchumacher thanks for the contribution

**Pull request merged**
