### PR TITLE
Update task.json

### PR DESCRIPTION
**Pull request by JSalter2013**
Fixed small UI typo - changed "Test Errors as Warnings" to "Treat Errors as Warnings"

### CODE REVIEW

**Comment by rfennell** [comment]
Thanks for the PR

Would you mind also editing the Extensions Readme to add a line along the lines of

2.2 Fixed Typo (PR#283)

I know I could do it, but if is in your PR you will appear as the contributor in the Squashed commit as opposed to me.

**Comment by rfennell** [comment]
Sorry I did not explain myself, I meant add the readme.md edit to this  PR as a second commit.

I don't want to waste your time any more, so don't worry I will merge the two PRs and sort it all out, hopefully tomorrow

**Comment by JSalter2013** [comment]
Sorry about that, I'm pretty new to using git. I've added the readme.md to this PR and closed off the other one.

**Comment by rfennell** [comment]
The changes are live as 2.2.2, I only incremented the final . version as I was testing my release pipeline and needed to do two releases

Thanks for the contribution

**Pull request merged**
