### PR TITLE
Replacing entire version tag instead of a specific matched version number

### PR DESCRIPTION
**Pull request by esbenbach**
Modified the replacing part of the task so it now replaces entire tags and not just the matching version number.

It should solve Issue #176 - but it might break other things.

### CODE REVIEW

**Comment by ChrisLGardner** [comment]
I've done some testing with this and it works pretty well other than one small use case, which is if I specify the field I want to update and it already exists. If you can resolve the merge conflict we're seeing by rebasing onto master (I made some other changes while this PR was around) then I'll merge this in and deal with the small use case mentioned above as I've got a fix for that working in a test branch.

**Comment by esbenbach** [comment]
Ill try solving the conflict - not entirely sure on how to go about rebasing across repos though.

**Comment by esbenbach** [comment]
Note 100% sure I did it correctly (given that all sorts of comments suddenly appeared here).

**Comment by ChrisLGardner** [comment]
That's a little odd that it's caused all those commits to appear. I'll merge it into a test branch and see what happens.

**Comment by ChrisLGardner** [comment]
I've done some testing and it looks good to me. I'll merge this and try to get a new release out later today.

**Pull request merged**
