### PR TITLE
Adding Code Coverage output support and updating to Pester 4.0.6

### PR DESCRIPTION
**Pull request by ChrisLGardner**
Adds the Code Coverage input for Invoke-Pester and outputs the XML file.

### CODE REVIEW

**Comment by ChrisLGardner** [comment]
Just added -CodeCoverage as I'd missed it, no use in generating a report if Pester isn't actually doing the code coverage analysis. It needs a bit more work as it currently just looks up the $ScriptFolder for any *.ps1 and adds those to -CodeCoverage. I'll look into it further and put some tests in too.

**Comment by ChrisLGardner** [comment]
In test builds it's correctly generating the xml file and publishing it via the dedicated task for it. I'll look into providing another input to specify location of files being analysed. I'll probably default it to the same location as $ScriptFolder but want to support people having different test steps for different groups of tests, such as unit tests and integrations tests in different folders (as seen on the DSC resources repos).

**Comment by scriptkiddie123** [comment]
Nice to see this feature on it's way.
On the pester README.md they have a nice image of what it JaCoCo output brings to VSTS/TFS: https://github.com/pester/Pester#code-coverage

**Comment by ChrisLGardner** [comment]
Pester 4.0.7 (and now 4.0.8) is out which is the official release of it so I'll get started on finishing this up a bit soon. 

I'll probably rev up to a new major version as the updating to the latest version of Pester will potentially break existing builds/releases.

**Pull request merged**
