### PR TITLE
Update included version of Pester to 4.3.1

### PR DESCRIPTION
**Pull request by JPRuskin**
### What problem does this PR address?
This pull request updates the included versions of Pester to include 4.3.1, overwriting the previous 4* version (4.0.8).
  
### Is there a related Issue?
#286 
  
### Have you...
I have not added the requisite line to the readme.md, as I have also submitted another pull request with the line and am unsure which will require less discussion - hopefully, everything seems reasonable / I've made no particularly awful errors, and we can add "Also updates Pester" to the line. I have enabled maintainer access.

### CODE REVIEW

**Comment by rfennell** [comment]
Thanks for the Pr, firstly to let you know I am away this week so won't be able to look at a merge until after Easter.

I do have one initial thought on the pr,  should the task support both 4.0.8 and 4.3.1, thoughts?

**Comment by JPRuskin** [comment]
I did consider it originally, but after rubber-ducking for a while (and looking at the changes I linked in the original comment) couldn't figure anything that _should_ break with the upgrade. If it was 5*, I would have left it, but I don't believe it would add value to include both at this point.

**Comment by rfennell** [comment]
Yes I agree, I will test the pr against my release pipeline as soon as I am back home

**Comment by rfennell** [comment]
Thanks for the PR it has been released as 7.0.1 
I had done a trial release of an updated CI/CD pipeline (so did a couple of test prebuilds 6.3.x) but realised that the revised dropdown choice causes existing builds to need an edit. As this is in effect a breaking change I updated major version

**Pull request merged**
