### PR TITLE
[FIX] The converted JSON string is in bad format

### PR DESCRIPTION
**Pull request by insanity13**
Information http://stackoverflow.com/questions/23552000/convertto-json-throws-error-when-using-a-string-terminating-in-backslash

### CODE REVIEW

**Comment by rfennell** [comment]
I can't see how this will effect any errors in the format of the json, I suspect that the issue is you experienced is fixed with defaultcredentials changes you made in the related pull request

**Comment by rfennell** [comment]
As @insanity13 pointed out in the Issue #80 this -compress flag seems to be PS version issues.

I am going to place this on hold for now and not pull it into the master as I don't think it is essential (but not going to close the pull request for now). I want to see if the issue effect others, now we have the related authorisation fixed in 1.2.x

**Comment by insanity13** [comment]
Are there some plans to merge changes?

**Comment by rfennell** [comment]
My apologies, been a bit busy, I will get it sorted this week

**Pull request merged**
