### PR TITLE
Upgrade to StyleCop 5.0

### PR DESCRIPTION
**Pull request by thomasddn**
Hi,

This PR will upgrade StyleCop to v5.0, which brings support for C# 7.0 syntax. While the unit tests in https://github.com/rfennell/StyleCopCmdLine/pull/8 all succeed, I'm having trouble to succeed with 2 tests:

- Test "File has 1 SA1650 issue" fails because it does not find an error.
- The folder test fails because it expects 40 errors, while only 39 are found.

I don't understand where the differences come from. I copied over the new StyleCop* and StyleCopWrapper DLL's, but no luck. Like I said, the tests in the StyleCopCmdLine do run successfully.

If someone has a clue, I'm happy to apply the change and add it to the PR.

### CODE REVIEW

**Comment by ChrisLGardner** [comment]
If I run the command manually I get the correct number of errors. Diff'ing the log files shows that the following is the error that isn't being picked up when it's run in the Pester tests:

    <Violation Section="Root.AllEnabled.FileWithTypo.JoinNames%string%string" LineNumber="17" Source="C:\Source\test\vNextBuild\Tests\Extensions\StyleCopTask\TestData\StyleCopSample\AllEnabled\FileWithTypo.cs" RuleNamespace="StyleCop.CSharp.DocumentationRules" Rule="ElementDocumentationMustBeSpelledCorrectly" RuleId="SA1650">The documentation text within the summary tag contains incorrectly spelled words: 'Joinsnames'</Violation>

How to then catch that in the tests is a little more difficult. I'll  try to do some digging when I get a chance.

**Comment by thomasddn** [comment]
Hi @ChrisLGardner,

Were you able to get around this weird issue? It would be great to see the PR merged and released to VSTS.

**Comment by ChrisLGardner** [comment]
Unfortunately I've been pretty busy with a few other projects so haven't had a chance. It might be next week before I get a good look at this.

**Comment by rfennell** [comment]
Not sure why I had to fix that conflict with ,gitignore from master (updated for other extensions) twice

**Comment by rfennell** [comment]
As discussed in #202 I have done a bit of restructuring and updating the CI process and am actively looking into the two test issues.

I think part of the problem could be that the task uses the [StyleCopCmdLine](https://github.com/rfennell/StyleCopCmdLine) codebase. This has never been update to StyleCop 5. I suspect this is a factor. StyleCop does not seem to like dynamic version binding too much

**Comment by thomasddn** [comment]
I also made a [pull request for StyleCopCmdLine](https://github.com/rfennell/StyleCopCmdLine/pull/8) to upgrade it to StyleCop 5.

**Comment by rfennell** [comment]
@thomasddn  sorry missed that thanks. I will sort that first

**Comment by rfennell** [comment]
OK made some progress, both the failing tests are 32/64bit related. Previously you had to force evaluation to 32bit if you wanted to load the dictionary DLL. 

This no longer seems to be the case, in fact it is the other way around, if you try to run tests in an architecture other than the current processor type it fails.

I have the test passing  locally, and as part of my CI/CD pipeline if I use an build agent hosted on my development PC. However, if I use VSTS hosted build agents the tests still fail. 

I want to try to stabilise this before continuing with the release

**Comment by rfennell** [comment]
@thomasddn , an update, I have been doing a good deal of digging over this in the past few days. This is a strange one

- I have merged your PR for the stylecopcmdline project to upgrade to StyleCop 5. The unit tests in this project all passing including the one for SA1650 (spell check). Thank you for the PR.
- I have taken the output from the stylecopcmdline project and used them within this VSTS Stylecop extension. I have also done some refactoring of the repo structure (#202). On my working branch I can run the Pester based tests locally (editing in VSCode and running invoke-pester from the integrated console) All the tests now pass using StyleCop 5 shipped in the task. Importantly this is now without and need to fiddle with X86/X64 as long as I use Pester 4.0.8, I get issues with Pester 3.4.0, the default with VS2017.
- However the SA1650 based tests fail on a hosted & vs2017 build agents in my CI/CD pipeline, but seem to pass if I use a private agent on my development PC. I suspect a Pester version issue here.
- As I suspect the issue is with Pester versions and x84/x64, and specifically how my Pester VSTS task loads modules, I have spent some time digging into this to make sure it is running the version of Pester. Not solved as yet, but improved the loading logic and tests, @ChrisLGardner  might want some help on this at present it is just a private release.
- Given I think the issue more Pester test related and StyleCop I decided a better tactic might be looking at using functional test in the CI/CD pipeline, testing the actual StyleCop task directly after deployment as private release. Did this and seems the SA1650 was just not being run, at all, as seen elsewhere. So I went back to VS2017 and opened my test solution, used for the functional test, and ran StyleCop 5 (installed via marketplace) in VST2017 and guess what ? SA1650 still was not picked up. 

I think the issue is there are not dictionaries shipped with StyleCop 5 via the marketplace.

So given all this I can release a V2 version of this Stylecop VSTS task (your PR and my refactors and readme updates), I up'd the major version so people have the choice to use 4.7 or 5.0 of StyleCop, but there is still a known issue with SA1650 dictionary based tests.

Thoughts?

**Comment by rfennell** [comment]
Bit more info on Pester tests front (FYI for @ChrisLGardner who is looking at the Pester issues)

- If I open a x86 Powershell prompt (%SystemRoot%\syswow64\WindowsPowerShell\v1.0\powershell.exe) I get the two failing tests as we have seen.
- If I open x64 Powershell prompt (the default on my Windows 10 (1709 build) PC all my tests pass.

From this I can infer that the issue is that under pester the stylecop 5 dictionary loading only works X64, this seems to be the opposite of previous  4.7 version.

I am currently working with the x86 version of VSCode, I will check to see what the new x64 does, also this information gives a bit more to go on over the automated CI builds

**Comment by rfennell** [comment]
OK, this is where I am up to. The extension builds and passes the pester tests (in the build) as long as I use my local development as the build agent. However it fails to pass the SA1650 based tests on the hosted build agents (both the older version and vs2017). This is even after modifying the Pester test runner to force the loading of the current version of pester.

However I have improved my deployment testing, and I now use the newly built task to do stylecop analysis of a sample project, this too is failing to see SA1650 violations.

I then went back to testing my sample files with the VS2017 Stylecop 5 extension. This too fails too. I have [logged an issue about this on the StyleCop repo](https://github.com/StyleCop/StyleCop/issues/158)

So we are at an interesting point
- We could release 2.x of the StyleCop extension, but it seems it will not find SA1650 violations, but neither does the VS2017 extension.
- As the extension is a major update, people do at least have the option to stick with the old v1.0 that uses Stylecop 4.7

At present I am holding off to see if I get any response from the StyleCop 5 team

**Comment by thomasddn** [comment]
Thanks for this in depth analysis! However, can you elaborate a bit more on how the dictionary loading works exactly? Which files (in what location) are being used for this?

I can confirm that the Stylecop 5 VS tool is not detecting SA1650 violations.

You could release 2.x with the following options:

- Mention the SA1650 ignorance as a known issue in Stylecop 5. You could point to your stylecop github issue.
- Release 2.x as beta.
- When Stylecop fixes the issue, reference the new version and release as final.

How do most people use Stylecop and CI? If they both use the VS Tool and CI, then they won't even notice the difference (SA1650 will be ignored in all environments). If they solely rely on CI for Stylecop, then it could be an issue.

**Comment by rfennell** [comment]
I think the loading of dictionaries is a bit of a dark art. 

From what I can work out you need to have

- mssp7en.dll
- mssp7en.lex
- StyleCop.Csharp.dll
- StyleCop.Csharp.rules.dll

in the same folder as StyleCop.Dll. With Stypecop 4.7 you also had to run the analysis in X32. However with StyleCop 5 you seem to need to run x64. 

I have put logic in to force x32/x64 operations, but I am missing something as I get different results on my own dev PC and a hosted build agent for dictionary based tests.

As to the VS2017 extension they have all the right files in the VSIX folder, but VS IDE is 32bit so I suspect that is their problem for the SA1650 rule

I agree it is worth get your PR and my edits for StyleCop 5 out with the know limitations. I will get onto it today.

**Comment by rfennell** [comment]
This has been worked on locally by myself, I ended put doing a squash/merge via #210 
This is now live as StyleCop extension 2.0.28.

I will keep an eye on Stylecop 5 release to see if we get anything on the SA1650 front.

Thanks for the PR, sorry it ended up being so drawn out at my end

**Comment by Parastou** [comment]
Hi,

Recently, on July 3rd, we upgraded our Stylecop form version 4.7.53 to the version 5.0.0.. With this new version of Stylecop for some developers, 1650(misspelling) is not detected, but for some it works. In both cases, Visual studio 2017 Professional has been installed, environment is windows 10 too. 
Is there any issues we should be considered?

I would appreciate your help.

**Comment by rfennell** [comment]
Sorry this has been an strange one, that we never got to the bottom of.

All I can suggest is enabling full debugging (in the build set system.debug=true), also do a file by file comparison of the working and non working dev PCs

As I mentioned before, we have moved our focus to SonarQube, so this has not been a major concern for our projects, and this seems to be the direction of movement of SytleCop analysis tools

**Comment by oleg-moroka** [comment]
We faced the same issue on our side  using version 5.0.0 .
SA1650 works on some PCs with VS2017 but in some PC  with VS2017 it doesn't.

**Comment by rfennell** [comment]
I fear we won't get a way to fix this until it becomes stable in VS2017

**Pull request closed without merging**
