### PR TITLE
Includes parent Work Items

### PR DESCRIPTION
**Pull request by SWarnberg**
Added code to include parent Work Item on Tasks and Bugs.
Also, added two new parameters, **wiFilter** and **wiStateFilter**, that can be used to filter the included Work Items.

### CODE REVIEW

**Comment by rfennell** [comment]
Sorry it has taken me a while to get to look at this, I have been off work due to sickness.

On a quick first look I see the commit contains a number of edits to manifest files that include special token that are used as part of the CI/CD process. These will need to be unwound so I can use my formal release process.

I will do local build and check the rest of the PR out and get back to you

**Comment by rfennell** [comment]
Nice bit of work, the one change I am going to make is to put in an extra flag so a user gets to choose between the previous (default) functionality and the you new options. I don't like to introduce breaking changes.

**Comment by SWarnberg** [comment]
Sounds great.
Yes, I needed to change some of the tokens to be able to test it locally. I should have reverted that.
My idea was that the new parameters could be "optional" by the [Task versioning](http://www.codewrecks.com/blog/index.php/2017/02/04/task-versioning-for-tfs-vsts-build/), but a flag works too.
Merry Christmas!

**Comment by rfennell** [comment]
This PR has been merged as part of PR #231 which enhances the code in this PR with a feature flag and other enhancements. 

Released as 2.12.5

@SWarnberg  thanks the work that kicked this enhancement off

**Pull request closed without merging**
